name: Add Header to Markdown Files

on:
  push:
    branches:
      - new_Branch
    paths:
      - 'combined/*.md'  # Update folder name

jobs:
  add_header:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Header to Markdown Files
        run: |
          for file in combined/*.md; do
            # Check if the file starts with a YAML front matter
            if [[ $(head -n 1 "$file") != '---' ]]; then
              echo "Header not found in $file. Skipping..."
              continue
            fi

            # Update last_updated timestamp in the header
            last_updated=$(date "+%B %d, %Y")
            sed -i "s/^last_updated:.*/last_updated: $last_updated/" "$file"
          done

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Matze2402"
          git add combined/*.md
          git diff --cached --exit-code || git commit -m "Update last_updated timestamp in Markdown files"
          git push
