name: Add Header to Markdown Files

on:
  push:
    branches:
      - new_Branch
    paths:
      - 'combined/*.md'  # Update folder name

jobs:
  add_header:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Header to Markdown Files
        run: |
          for file in combined/*.md; do
            title=$(grep -m 1 '## ' "$file" | sed 's/^## //')
            last_updated=$(date -r "$file" "+%B %d, %Y")
            permalink=$(basename "$file" .md).html

            echo '---' > tmpfile
            echo "title: $title" >> tmpfile
            echo 'tags: [ontology]' >> tmpfile
            echo 'keywords: NFDI4Cat, Ontology, Ontology World Map, NFDI for catalysis related research, semantic web' >> tmpfile
            echo "last_updated: $last_updated" >> tmpfile
            echo 'datatable: true' >> tmpfile
            echo 'summary:' >> tmpfile
            echo 'sidebar: mydoc_sidebar' >> tmpfile
            echo "permalink: $permalink" >> tmpfile
            echo 'folder: combined' >> tmpfile
            echo '---' >> tmpfile
            cat "$file" >> tmpfile
            mv tmpfile "$file"
          done

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "matze2402"
          git add combined/*.md
          git diff --cached --exit-code || git commit -m "Add header to Markdown files"
          git push
