name: Delete Files

on:
  workflow_run:
    workflows: ["push_to_another_branch"]
    types:
      - completed

jobs:
  delete-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Delete all files from a folder
        run: rm -rf combined/*
