name: push_to_another_branch

on:
 repository_dispatch:
    types: [push-md]
 

jobs:
  job2:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'combined'
          TARGET_BRANCH: 'new_Branch'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'MAtze2402'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch


      - name: Dispatch trigger for deleting
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ADMIN }}
          repository: Matze2402/temp_repo
          event-type: push 
