name: Push Folder to Another Repository

on:
  push:
    branches:
      - main

jobs:
  push-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone target repository
        run: git clone https://github.com/matze2402/main_repo.git main_repo

      - name: Copy folder to target repository
        run: |
          cp -r combined/* main_repo/alles
          cd main_repo
          git config --local user.email "action@github.com"
          git config --local user.name "matze2402"
          git config --global url.https://${{ secrets.admin}}@github.com/.insteadOf https://github.com/
          git add .
          git commit -m "Copy files from source repository"
          git config pull.rebase false
          git pull origin github_io_pages
          git push origin main:github_io_pages

      - name: Check for merge conflicts
        id: check_conflicts
        run: |
          git merge-base --is-ancestor HEAD FETCH_HEAD || exit 0
          exit 1

      - name: Resolve merge conflicts
        if: steps.check_conflicts.outcome == 'failure'
        run: git mergetool
