name: Convert Word to Markdown

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Convert Word to Markdown
        run: |
          for file in combined/*.docx; do
            pandoc "$file" -o "${file%.docx}.md"
            rm "$file"
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4              
        with:
          commit_message: "Convert Word to Markdown"
          commit_options: '--no-verify'

  job2:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: job1
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'combined'
          TARGET_BRANCH: 'new_Branch'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'MAtze2402'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          for file in $SRC_FOLDER_PATH/*.md; do
            git checkout ${GITHUB_REF##*/} -- "$file" # copy Markdown files from the source branch
            git add "$file"
          done
          git diff-index --quiet HEAD || git commit -am "Convert Word to Markdown"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch

  
