name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Convert Word to Markdown
        run: |
          for file in combined/*.docx; do
            pandoc "$file" -o "${file%.docx}.md"
            rm "$file"
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Convert Word to Markdown"
          commit_options: '--no-verify'

  
